### ISSUE TITLE
Dehydration incompat

### ISSUE THREAD

**Issue by Laifsyn** [ZestyBlaze/Malus-Phaethusa#2]
I've set the enchanted milks as a hydrating food, but I can't get hydrated when drinking the golden milks

**Comment by Laifsyn** [comment]
1.18.1 MC
Mod loader 0.13.3

**Comment by ZestyBlaze** [comment]
Hiya, sorry for the delay, I'll have to take a look into this but I don't think there would be a way for me to fix this on my end, might be worth checking this on their end too
